services:
  - type: web
    name: server-2
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorm backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000 --timeout 120"
    envVars:
      #Django Core
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-5h=(s6a5on^k)(ul!y7kh)mnhm26vuq93r1ix#!kw^zkt0cte2"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"

        # Database (Supabase)
      - key: DB_NAME
        value: "postgres"
      - key: DB_USER
        value: "postgres.miornhcxxzxecwnkgupq"
      - key: DB_PASSWORD
        value: "betaTrident1@" 
      - key: DB_HOST
        value: "aws-0-ap-southeast-1.pooler.supabase.com"
      - key: DB_PORT
        value: "6543"
      - key: DB_OPTIONS
        value: '{"connect_timeout": 5, "sslmode": "require"}' 

      # CORS
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:5173"

      # Static Files
      - key: STATIC_URL
        value: "/static/"