name: CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]  

jobs:
  # --- Frontend Job ---
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: Run Tests
        run: |
          if grep -q '"test":' ./web/package.json; then
            npm run test -- --watchAll=false --if-present
          else
            echo "No test script found, skipping tests"
          fi

  test-mobile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: Run Tests
        run: |
          if grep -q '"test":' ./mobile/package.json; then
            npm test -- --watchAll=false --if-present
          else
            echo "No test script found, skipping tests"
          fi
  
  # --- Backend Job ---
  test-server-1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-1
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - run: python manage.py test

  test-server-2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-2
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL2 }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY2 }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY2 }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET2 }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY2 }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID2 }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - run: python manage.py test