name: CI Pipeline
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # --- Frontend Job ---
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - name: Run Tests
        run: |
          if grep -q '"test":' ./web/pacakge.json; then
            npm run test -- --watchAll=false --if-present
          else
            echo "No test script found, skipping tests"
          fi  

  test-mobile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - name: Run Tests
        run: |
          if grep -q'"test":' ./mobile/package.json; then
            npm test -- --watchall=false --if-prensent
          else
            echo "No test script found, skipping tests"
          fi


  # --- Backend Job ---
  test-server-1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - run: python manage.py test

  test-server-2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - run: python manage.py test
